### PR TITLE
Avido/shipping options

### PR DESCRIPTION
**Pull request by avido**
## Description

Added delivery options: 
- age_check
- insurance

Added delivery Types
- morning
- evening
- express

## Motivation and context

- Age_check & insurance weren't available.
- Delivery Types were missing mandatory delivery_date
- Added easier access to deliveryTypes such as morning/evening

## How has this been tested?

See unit tests

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

*This change shouldn't be breaking however by adding the Nesbot\Carbon package unexpected results could occure.

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked.

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ ] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] If my change requires a change to the documentation, I have updated it accordingly.
- [x] My code follows the code style of this project.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by mvdnbrk** [comment]
Thanks for your PR!

This PR addresses multiple new features at once.
Please address only one new feature per pull request.

Second, the tests added were not passing.

Closing this for now.

**Comment by avido** [comment]
Hi,

The tests are not passing because of missing environment var.

**Comment by mvdnbrk** [comment]
```
Error: Class 'Carbon\Carbon' not found
```

**Comment by avido** [comment]
> ```
> Error: Class 'Carbon\Carbon' not found
> ```

Missed that one.. Is the automation running a composer update ? As the package is included in the composer file

**Comment by mvdnbrk** [comment]
Ah yeah, that's probably the reason.

Still I don't want to add the `nesbot/carbon` package as a required dependency.
I think using `DateTimeInterface` is a better solution here.

**Pull request closed without merging**
