### PR TITLE
Added two attributes to the Trace Resource Class

### PR DESCRIPTION
**Pull request by ZenoWebdev**
## Description

Added two attributes to the Trace Resource Class
## Motivation and context

Solves issue #39 

## How has this been tested?

We did a tracktrace call that succesfully returned the two new attributes. [Ubuntu20.04, PHP7.4.7]

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked.

- [ x ] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ x ] My pull request addresses exactly one patch/feature.
- [ x ] I have created a branch for this patch/feature.
- [ x ] Each individual commit in the pull request is meaningful.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] If my change requires a change to the documentation, I have updated it accordingly.
- [ x ] My code follows the code style of this project.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by mvdnbrk** [comment]
These attributes should be on the `TrackTrace` class.

**Comment by mvdnbrk** [comment]
Seems like the values of `link_consumer_portal` and `link_tracktrace` are identical.
I would prefer to only add one link unless there is a good reason to add them both.

Secondly I would prefer to call the attribute `link` for simplicity; `link_tracktrace` is redundant here on the `TrackTrace` class:

```
$tracktrace->link
```

**Comment by ZenoWebdev** [comment]
They are in fact not identical. The ```link_consumer_portal``` is the link to the track and trace portal of MyParcel. The ```link_tracktrace``` is the link of the shipment provider itself (e.g. postnl/dhl). As documented here [https://myparcelnl.github.io/api/#6_G_4](url)

**Comment by mvdnbrk** [comment]
That make sense however the results I get back from the MyParcel API are the same for both attributes.
For example: `https://postnl.nl/tracktrace?B=3SMYPA...`

**Comment by ZenoWebdev** [comment]
Did you activated the portal at the My Parcel settings?

**Comment by mvdnbrk** [comment]
I was not aware of this setting, well then it makes sense to add both the links.

**Comment by mvdnbrk** [comment]
Changed the implementation a bit and merged.

Thanks!

**Pull request merged**
